language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t oddsha/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true oddsha/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-690051687500"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 
